#!/bin/bash

# NexusCare Local Database Setup Script
# This script automates the local PostgreSQL database setup

set -e  # Exit on error

echo "🏥 NexusCare Local Database Setup"
echo "=================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
DB_NAME="nexuscare"
DB_USER="nexuscare_user"
DB_PASSWORD="nexuscare_dev_password"
DB_HOST="localhost"
DB_PORT="5432"

# Step 1: Check if PostgreSQL is installed
echo "📋 Step 1: Checking PostgreSQL installation..."
if ! command -v psql &> /dev/null; then
    echo -e "${RED}❌ PostgreSQL is not installed${NC}"
    echo "Please install PostgreSQL first:"
    echo "  sudo apt-get install postgresql postgresql-contrib"
    exit 1
fi
echo -e "${GREEN}✅ PostgreSQL is installed${NC}"
echo ""

# Step 2: Check if PostgreSQL is running
echo "📋 Step 2: Checking PostgreSQL service..."
if ! sudo systemctl is-active --quiet postgresql; then
    echo -e "${YELLOW}⚠️  PostgreSQL is not running. Starting it...${NC}"
    sudo systemctl start postgresql
    sleep 2
fi
echo -e "${GREEN}✅ PostgreSQL is running${NC}"
echo ""

# Step 3: Create database
echo "📋 Step 3: Creating database..."
if sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw $DB_NAME; then
    echo -e "${YELLOW}⚠️  Database '$DB_NAME' already exists${NC}"
    read -p "Do you want to drop and recreate it? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        sudo -u postgres psql -c "DROP DATABASE $DB_NAME;"
        sudo -u postgres psql -c "CREATE DATABASE $DB_NAME;"
        echo -e "${GREEN}✅ Database recreated${NC}"
    fi
else
    sudo -u postgres psql -c "CREATE DATABASE $DB_NAME;"
    echo -e "${GREEN}✅ Database created${NC}"
fi
echo ""

# Step 4: Create user
echo "📋 Step 4: Creating database user..."
if sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1; then
    echo -e "${YELLOW}⚠️  User '$DB_USER' already exists${NC}"
else
    sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
    echo -e "${GREEN}✅ User created${NC}"
fi
echo ""

# Step 5: Grant privileges
echo "📋 Step 5: Granting privileges..."
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
sudo -u postgres psql -d $DB_NAME -c "GRANT ALL ON SCHEMA public TO $DB_USER;"
sudo -u postgres psql -d $DB_NAME -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DB_USER;"
sudo -u postgres psql -d $DB_NAME -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $DB_USER;"
sudo -u postgres psql -d $DB_NAME -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DB_USER;"
sudo -u postgres psql -d $DB_NAME -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $DB_USER;"
echo -e "${GREEN}✅ Privileges granted${NC}"
echo ""

# Step 6: Test connection
echo "📋 Step 6: Testing database connection..."
if PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -d $DB_NAME -h $DB_HOST -c "SELECT version();" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Database connection successful${NC}"
else
    echo -e "${RED}❌ Database connection failed${NC}"
    echo "You may need to configure pg_hba.conf for password authentication"
    exit 1
fi
echo ""

# Step 7: Create .env file
echo "📋 Step 7: Creating .env file..."
if [ -f .env ]; then
    echo -e "${YELLOW}⚠️  .env file already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping .env creation"
    else
        create_env=true
    fi
else
    create_env=true
fi

if [ "$create_env" = true ]; then
    # Generate keys
    JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')
    ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n')
    ENCRYPTION_SALT=$(openssl rand -base64 32 | tr -d '\n')
    
    cat > .env << EOF
# =============================================================================
# NexusCare Backend - Local Development Configuration
# =============================================================================
# Generated by setup_local_db.sh on $(date)

# =============================================================================
# Server Configuration
# =============================================================================
SERVER_HOST=0.0.0.0
SERVER_PORT=8080
API_BASE_URL=http://localhost:8080

# =============================================================================
# PostgreSQL Database (Local)
# =============================================================================
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME
DATABASE_MAX_CONNECTIONS=10
DATABASE_TIMEOUT_SECONDS=30

# =============================================================================
# JWT Authentication
# =============================================================================
JWT_SECRET=$JWT_SECRET
JWT_EXPIRY_HOURS=24
JWT_REFRESH_EXPIRY_DAYS=30

# =============================================================================
# Encryption (AES-256-GCM)
# =============================================================================
ENCRYPTION_KEY=$ENCRYPTION_KEY
ENCRYPTION_SALT=$ENCRYPTION_SALT

# =============================================================================
# Paystack Payment Gateway (Test Mode)
# =============================================================================
# Get your test keys from: https://dashboard.paystack.com/#/settings/developer
PAYSTACK_SECRET_KEY=sk_test_your_paystack_secret_key_here
PAYSTACK_PUBLIC_KEY=pk_test_your_paystack_public_key_here
PAYSTACK_API_URL=https://api.paystack.co
PAYSTACK_WEBHOOK_SECRET=your_webhook_secret_here

# =============================================================================
# Geocoding Service (Nominatim/OpenStreetMap)
# =============================================================================
GEOCODING_API_URL=https://nominatim.openstreetmap.org
GEOCODING_USER_AGENT=NexusCare/1.0 (dev@nexuscare.com)
GEOCODING_RATE_LIMIT=1
GEOCODING_MAX_RETRIES=3
GEOCODING_RETRY_DELAY_MS=1000

# =============================================================================
# Email Service (SMTP) - Configure for real emails
# =============================================================================
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-app-specific-password
SMTP_FROM_EMAIL=noreply@nexuscare.com
SMTP_FROM_NAME=NexusCare Platform
SMTP_USE_TLS=true

# =============================================================================
# Push Notifications (Firebase Cloud Messaging) - Optional
# =============================================================================
FCM_SERVER_KEY=your_firebase_server_key_here
FCM_PROJECT_ID=your_firebase_project_id
FCM_SERVICE_ACCOUNT_PATH=./config/firebase-service-account.json

# =============================================================================
# File Storage (Local for development)
# =============================================================================
STORAGE_PROVIDER=local
STORAGE_LOCAL_PATH=./uploads
STORAGE_MAX_FILE_SIZE_MB=10

# =============================================================================
# Logging
# =============================================================================
RUST_LOG=nexuscare_backend=debug,tower_http=debug,sqlx=info
LOG_FORMAT=pretty
LOG_FILE_PATH=./logs/nexuscare.log

# =============================================================================
# CORS Configuration
# =============================================================================
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
CORS_ALLOW_CREDENTIALS=true

# =============================================================================
# Rate Limiting
# =============================================================================
RATE_LIMIT_PER_MINUTE=60
RATE_LIMIT_BURST=10

# =============================================================================
# Application Settings
# =============================================================================
APP_ENV=development
ENABLE_API_DOCS=true
ENABLE_REQUEST_LOGGING=true
DEFAULT_SERVICE_RADIUS_KM=5.0

# =============================================================================
# Security
# =============================================================================
BCRYPT_COST=12
SESSION_TIMEOUT_MINUTES=30
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_DURATION_MINUTES=15
EOF
    
    echo -e "${GREEN}✅ .env file created with generated keys${NC}"
    echo ""
    echo -e "${YELLOW}⚠️  IMPORTANT: Update these values in .env:${NC}"
    echo "  - PAYSTACK_SECRET_KEY (get from https://dashboard.paystack.com)"
    echo "  - PAYSTACK_PUBLIC_KEY (get from https://dashboard.paystack.com)"
    echo "  - SMTP_USERNAME (your Gmail address)"
    echo "  - SMTP_PASSWORD (Gmail app password)"
fi
echo ""

# Step 8: Install sqlx-cli if needed
echo "📋 Step 8: Checking sqlx-cli..."
if ! command -v sqlx &> /dev/null; then
    echo -e "${YELLOW}⚠️  sqlx-cli not found. Installing...${NC}"
    echo "This may take a few minutes..."
    cargo install sqlx-cli --no-default-features --features postgres
    echo -e "${GREEN}✅ sqlx-cli installed${NC}"
else
    echo -e "${GREEN}✅ sqlx-cli is already installed${NC}"
fi
echo ""

# Step 9: Run migrations
echo "📋 Step 9: Running database migrations..."
if sqlx migrate run; then
    echo -e "${GREEN}✅ Migrations completed successfully${NC}"
else
    echo -e "${RED}❌ Migration failed${NC}"
    echo "Check the error messages above"
    exit 1
fi
echo ""

# Step 10: Create necessary directories
echo "📋 Step 10: Creating necessary directories..."
mkdir -p uploads logs config
echo -e "${GREEN}✅ Directories created${NC}"
echo ""

# Summary
echo "=================================="
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "=================================="
echo ""
echo "Database Information:"
echo "  Database: $DB_NAME"
echo "  User: $DB_USER"
echo "  Password: $DB_PASSWORD"
echo "  Host: $DB_HOST"
echo "  Port: $DB_PORT"
echo ""
echo "Connection String:"
echo "  postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"
echo ""
echo "Next Steps:"
echo "  1. Update .env with your Paystack and email credentials"
echo "  2. Run: cargo run"
echo "  3. Open: http://localhost:8080/api/docs"
echo ""
echo "Useful Commands:"
echo "  - Connect to database: psql -U $DB_USER -d $DB_NAME -h $DB_HOST"
echo "  - Run migrations: sqlx migrate run"
echo "  - Start server: cargo run"
echo "  - View logs: tail -f logs/nexuscare.log"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"
