pub mod audit;
pub mod billing;
pub mod clinician;
pub mod email_outbox;
pub mod feedback;
pub mod hospital;
pub mod identity_verification;
pub mod location;
pub mod patient;
pub mod shift;
pub mod wallet;

pub use audit::AuditRepository;
pub use billing::BillingRepository;
pub use clinician::{ClinicianRepoError, ClinicianRepository};
pub use email_outbox::EmailOutboxRepository;
pub use feedback::FeedbackRepository;
pub use hospital::HospitalRepository;
pub use identity_verification::{IdentityRepoError, IdentityVerificationRepository};
pub use location::LocationRepository;
pub use patient::PatientRepository;
pub use wallet::{WalletRepoError, WalletRepository};
